version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
  mongo_seed:
    build: ./db
    links:
      - mongo
