version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "80:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "7017:7017"
